### DISCUSSION TITLE
struggling with pulsar functions in kubernetes

### DISCUSSION THREAD

**Discussion by jesumyip** [apache/pulsar#18332] [General]
I'm getting an OpenSSLEngine general error in my pulsar function pods. I've narrowed it down to pulsar-admin that's causing this issue. We use cert-manager to secure our Pulsar instance.

Everytime I run pulsar-admin *manually* to create a function, I understand that this causes Pulsar to create a K8s manifest that deploys a pod to run my function. When I inspect the created pod, I see that it's got a few issues.

1. The shell command in the pod that instructs pulsar-admin to download my function (I'm using the example exclamation function written in Python), is not given any instruction to use a private root CA cert. How do I change this behaviour? I have seen documentation to modify /pulsar/conf/client.conf. But this is a manual step. I would expect Pulsar to actually modify this file for me or somehow use the correct cli parameters in the shell command that calls pulsar-admin. Is there somewhere I can configure this behaviour?
2. I can also see that there is no volume mounted in the pod that has the root CA cert at well. Again, how do I change this behaviour? 

Sorry for the basic questions as we are completely new to Pulsar.

**Comment by michaeljmarshall** [comment]
@jesumyip - in your function worker config, do you have `brokerClientTrustCertsFilePath` or `tlsTrustCertsFilePath` set? Based on reading through the code, that configuration is used to read the bytes into the function worker's memory, create a kubernetes secret, then mount that secret into the function pod.

This appears to be documented here: https://pulsar.apache.org/docs/next/functions-worker-run-separately/#enable-tls-encryption.

Here are some of the relevant code references:

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java#L607-L615

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java#L774-L785

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java#L221

(A couple skipped references, but it's easy to follow in an IDE.)

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProvider.java#L279-L287

**Reply by jesumyip** [reply]
@michaeljmarshall Reaaaaaaaallly appreciate the reply, Michael. Thank you!

So since this is running in a K8S cluster, I assume the function worker config is a configmap? I assume it is this?

<img width="880" alt="image" src="https://user-images.githubusercontent.com/87511866/199909139-fef43424-b625-48ec-9321-d610bf06d1a4.png">

So the other problem is if I do set say tlsTrustCertsFilePath, what path do I point it to? In the pod that runs the function, I have to mount a secret that contains the trusted root cert. There has to be a config somewhere else that does this for me?

**Reply by jesumyip** [reply]
The real issue for me seems to be - "How do I tell Pulsar so that when it generates the Kubernetes manifest that will deploy the Stateful set which runs the function, it also mounts / injects the appropriate CA cert into the pod?"

Based on what I can see above (I don't code in Java, but the code seems simple enough to understand), it first needs to read the file that contains the root CA. That's the part that I'm stumbling with. If I modify the configmap for `datastream-pulsar-functions-worker-config` (see screenshot above), and insert `tlsTrustCertsFilePath`, I have no idea what path / file to point it to.

I have tried editing that configmap and it does absolutely nothing. The new pod that gets created has no secrets mounted in that contains the root CA. ???

**Reply by michaeljmarshall** [reply]
How are you deploying Pulsar? It looks like you're using the helm chart. Which version, and do you mind sharing some/all of your values file?

**Reply by jesumyip** [reply]
@michaeljmarshall Yes, using helm. Our ops team created a helm subchart that combined pulsar,redis, and istio. 

Here are the values we use:

```
pulsar:
  enabled: true
  namespace: datastream
  initialize: true
  persistence: true
  volumes:
    persistence: true
    local_storage: false
  components:
    # zookeeper
    zookeeper: true
    # bookkeeper
    bookkeeper: true
    # bookkeeper - autorecovery
    autorecovery: true
    # broker
    broker: true
    # functions
    functions: true
    # proxy
    proxy: true
    # toolset
    toolset: true
    # pulsar manager
    pulsar_manager: false
  monitoring:
    # monitoring - prometheus
    prometheus: true
    # monitoring - grafana
    grafana: true
    # monitoring - node_exporter
    node_exporter: true
    # alerting - alert-manager
    alert_manager: true
  certs:
    internal_issuer:
      # use cert-manager to provision TLS certificates
      enabled: true
  tls:
    enabled: true
    common:
      organization:
        - "Test Demo"
    proxy:
      enabled: true
    broker:
      enabled: true
    bookie:
      enabled: true
    zookeeper:
      enabled: true
    autorecovery:
      enabled: true
    toolset:
      enabled: true
  auth:
    authentication:
      enabled: true
      jwt:
        # set to true if generated keys are symmetric; otherwise, false
        usingSecretKey: false
    authorization:
      enabled: true
    superUsers:
      # broker to broker communication
      broker: "broker-admin"
      # proxy to broker communication
      proxy: "proxy-admin"
      # pulsar-admin client to broker/proxy communication
      client: "admin"
  # component settings
  zookeeper:
    nodeSelector:
      workload: stream
    volumes:
      persistence: true
      data:
        name: data
        size: 20Gi
        local_storage: false
        storageClassName: regional-storage-pd-balanced
  bookkeeper:
    nodeSelector:
      workload: stream
    affinity:
      type: preferredDuringSchedulingIgnoredDuringExecution
    volumes:
      persistence: true
      useSingleCommonVolume:
      journal:
        name: journal
        size: 10Gi
        local_storage: false
        storageClassName: regional-storage-pd-balanced
      ledgers:
        name: ledgers
        size: 50Gi
        local_storage: false
        storageClassName: regional-storage-pd-balanced
  autorecovery:
    nodeSelector:
      workload: stream
    affinity:
      type: preferredDuringSchedulingIgnoredDuringExecution
  broker:
    nodeSelector:
      workload: stream
  proxy:
    nodeSelector:
      workload: stream
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
    affinity:
      anti_affinity: true
      type: preferredDuringSchedulingIgnoredDuringExecution
    service:
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
      type: LoadBalancer
    ingress:
      enabled: false
  dashboard:
    nodeSelector:
      workload: stream
  toolset:
    nodeSelector:
      workload: stream
  prometheus:
    nodeSelector:
      workload: stream
    volumes:
      persistence: true
      data:
        name: data
        size: 10Gi
        local_storage: false
        storageClassName: regional-storage-pd-balanced
  grafana:
    nodeSelector:
      workload: stream
    service:
      type: ClusterIP
    ingress:
      enabled: false
  pulsar_manager:
    nodeSelector:
      workload: stream
  
redis-ha:
  enabled: true
  nodeSelector:
      workload: cache

local-storage-provisioner:
  enabled: false

gateway:
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: None
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: pulsar
      port: 6650
      protocol: TCP
      targetPort: 6650
    - name: pulsar-ssl
      port: 6651
      protocol: TCP
      targetPort: 6651
    annotations:
      networking.gke.io/load-balancer-type: "Internal"
    loadBalancerIP: "<redacted>"
    loadBalancerSourceRanges: [<redacted>]
    externalTrafficPolicy: ""
    externalIPs: []
```
