### DISCUSSION TITLE
connect to broker in standalone mode via Kubernetes

### DISCUSSION THREAD

**Discussion by ShuAiii** [apache/pulsar#18772] [Q&A] [answered]
I'm running an app with 3 Kubernetes pods.

First pod: Pulsar standalone
Third pod: Producer
Second pod: Consumer

These 3 pods each have their own IP address, but they are all on the same network.

How do I connect the Producer and Consumer to the Pulsar standalone pod without explicitly giving them the IP of the standalone pod?

Thank you.

**Comment by nicoloboschi** [comment, marked as answer]
In kubernetes you should use a [Service](https://kubernetes.io/docs/concepts/services-networking/service/) resource for manage networking and put it in "front" of the pulsar pod. 
Then the producer and consumer will have to point to the service name. 

For example you can create a service like this
```
apiVersion: v1
kind: Service
metadata:
  name: pulsar-service
spec:
  clusterIP: None
  selector:
    app: pulsar
  ports:
    - name: client
      port: 6650
    - name: admin
      port: 8080
```

Assuming that your pod matches the label app=pulsar, then the producer and consumer will have to point to pulsar://pulsar-service:6650 (pulsar protocol) and http://pulsar-service:8080 (pulsar admin)

Another suggestion is to use a deployment instead of a raw pod.

Btw, for Pulsar in Kubernetes it's suggested to use a proper deployment process by using the helm chart or an operator.
At the moment there's a [Apache Pulsar Helm Chart](https://pulsar.apache.org/docs/2.10.x/helm-overview/)
