### DISCUSSION TITLE
[docs] Log4j configuration needs to be better documented

### DISCUSSION THREAD

**Discussion by devinbost** [apache/pulsar#18785] [Q&A]
We currently don't have much documentation around how to configure Log4j debugging for Pulsar, and the log4j docs are confusing. For example, I'm trying to enable DEBUG logging for Pulsar, but we're having trouble getting debug statements to show up in our rolling log. The Pulsar docs don't provide sufficient explanation around how to do this.

**Comment by devinbost** [comment]
For example, the following Log4j file doesn't emit debug statements for permits from `ConsumerImpl`, `Consumer`, or `PersistentDispatcherMultipleConsumers`

[log4j2.yaml.txt](https://github.com/apache/pulsar/files/6299567/log4j2.yaml.txt)
(Ignore the .txt extension. That was just to enable uploading it into the Github issue.)

**Comment by devinbost** [comment]
I was able to get debug statements after hard coding `"debug"` in place of `"${sys:pulsar.log.level}"` in this part of the log4j2.yaml file:
```
Root:
      level: debug
      additivity: true
      AppenderRef:
        - ref: "${sys:pulsar.log.appender}"
          level: "${sys:pulsar.log.level}"
        - ref: Prometheus
          level: info
```
However, I haven't been able to get debug logging on the functions.
