### DISCUSSION TITLE
How to set up Broker config and other configs like bookie etc

### DISCUSSION THREAD

**Discussion by Muraligowtham** [apache/pulsar#19276] [Q&A] [answered]
Hi All, I am new to pulsar and I am creating a pulsar cluster in aws EKS stack using helm charts.I have a question regarding how to set up broker conf and other conf via helm chart. or does it have to be done via java admin client?

can you pls provide clarity on how this can be achieved,

one of the error that i am getting is ,
[Request processing failed; nested exception is org.apache.pulsar.client.admin.PulsarAdminException$NotAllowedException: Topic level policies is disabled, to enable the topic level policy and retry.] with root cause

**Comment by lhotari** [comment, marked as answer]
### Configuring Pulsar Broker and Bookkeeper in Apache Pulsar Helm chart

Here's an example from the pulsar-helm-chart CI tests: https://github.com/apache/pulsar-helm-chart/blob/8ad7cf6b6508a23546a8d5a66e5319cf36f39712/.ci/clusters/values-broker-tls.yaml#L43-L60

```yaml
# these are values used in pulsar-helm-chart CI, they aren't examples of production settings
bookkeeper:
  replicaCount: 3
  configData:
    diskUsageThreshold: "0.999"
    diskUsageWarnThreshold: "0.999"
    PULSAR_PREFIX_diskUsageThreshold: "0.999"
    PULSAR_PREFIX_diskUsageWarnThreshold: "0.999"

broker:
  replicaCount: 1
  configData:
    ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
    ## without persistence
    autoSkipNonRecoverableData: "true"
    # storage settings
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
```

For the broker, use the `broker.configData` key in your `values.yaml`. If the key is in the default `broker.conf` file for a particular version of Pulsar ([broker.conf for 2.10.3](https://github.com/apache/pulsar/blob/v2.10.3/conf/broker.conf)), you can use the key directly. 
There are some special cases where the key is missing from the [broker.conf](https://github.com/apache/pulsar/blob/v2.10.3/conf/broker.conf) or [bookkeeper.conf](https://github.com/apache/pulsar/blob/v2.10.3/conf/bookkeeper.conf) file. In those cases, it's necessary to add `PULSAR_PREFIX_` to the configuration key.

The way this works is that a Python script [apply-config-from-env.py](https://github.com/apache/pulsar/blob/v2.10.3/docker/pulsar/scripts/apply-config-from-env.py) is used to apply environment variables found in the config file. If there's no match, for a key config, it's necessary to use an environment variable with `PULSAR_PREFIX_` to add the new key to the default template config file.
Here's how the pulsar-helm-chart uses apply-config-from-env.py as part of the command for the container: 
https://github.com/apache/pulsar-helm-chart/blob/8ad7cf6b6508a23546a8d5a66e5319cf36f39712/charts/pulsar/templates/broker-statefulset.yaml#L204

### Example of configuring `topicLevelPoliciesEnabled=true` in your `values.yaml`

`topicLevelPoliciesEnabled=true` requires setting `systemTopicEnabled=true`.

```yaml
broker:
  configData:
    systemTopicEnabled: "true"
    topicLevelPoliciesEnabled: "true"
```

**Reply by Khemendra-Bhardwaj** [reply]
I've noticed that many Pulsar broker configurations are missing from the official Apache Pulsar Helm chart. For example, configurations like loadBalancerSheddingEnabled and bundle splitting aren't included, though they are present in the official Pulsar repository.

Could someone guide me on how to add these configurations to the Helm chart so I can deploy a customized Pulsar setup with the desired broker configurations?

**Reply by lhotari** [reply]
@Khemendra-Bhardwaj That's a good question. When the key is missing from the `conf/broker.conf` file, you can add the configs to `broker.configData` with a key starting with `PULSAR_PREFIX_`. It's due to the Python script 
https://github.com/apache/pulsar/blob/master/docker/pulsar/scripts/apply-config-from-env.py which is used to apply the configuration from the environment. The Apache Pulsar Helm chart uses this script.

**Reply by Khemendra-Bhardwaj** [reply]
The key is present in conf/broker.conf file in apache pulsar repo
but not in apache pulsar helm repo

key : # Enable/disable automatic bundle unloading for load-shedding
loadBalancerSheddingEnabled=true

Should I add the key : 
PULSAR_PREFIX_loadBalancerSheddingEnabled= true 
to charts/pulsar/templates/broker-configmap.yaml   in pulsar helm repo ?

**Reply by lhotari** [reply]
> Should I add the key :
> PULSAR_PREFIX_loadBalancerSheddingEnabled= true
> to charts/pulsar/templates/broker-configmap.yaml in pulsar helm repo ?

No. For Helm charts, you usually pass a value.yaml file to configure the options. 
In your values.yaml, you could do this:
```yaml
broker:
  configData:
     loadBalancerSheddingEnabled: "true"
```
You don't need to have `PULSAR_PREFIX_` as the prefix for the key since `loadBalancerSheddingEnabled` exists in the default `conf/broker.conf` file in the docker image.
