### DISCUSSION TITLE
Bookie handle is not available -  ledger=22 - operation=Failed to read entry - entry=0

### DISCUSSION THREAD

**Discussion by youngerstyle** [apache/pulsar#20985] [Q&A] [answered]
I can't understand how this problem arises,
Several sudden power outages recently caused the pulsar on the server to stop. After each recovery, other services will report errors when accessing pulsar, so they can only be deployed again.

Environment: docker+standalone+data persistence

Can someone help me understand the possible reasons for this error? sincere thanks

**Comment by adrianlyjak** [comment]
Not an answer, but I'm running into a similar issue when running a standalone pulsar in a kubernetes test environments. After running for a while (potentially after the pods is restarted?), it starts getting this error. Restarting the pod doesn't help, it seems like the bookkeeper data is getting corrupted and is not able to recover. Since this is a test environment, I'm wondering if there's some setting to ignore entries that it cannot read, or some hints to look at to resolve.

This is when running docker image for `apachepulsar/pulsar:3.1.0`

stateful set is started up with this command using the standard `standalone.conf`

```yaml
  - command:
    - sh
    args:
    - -c
    - /pulsar/bin/apply-config-from-env.py /pulsar/conf/standalone.conf; exec /pulsar/bin/pulsar
      standalone -nfw;
```
