### DISCUSSION TITLE
Oxia

### DISCUSSION THREAD

**Discussion by eaba** [apache/pulsar#21039] [Q&A]
I want to replace the [#zookeeper](https://twitter.com/hashtag/zookeeper?src=hashtag_click) with [#oxia](https://twitter.com/hashtag/oxia?src=hashtag_click), which is not working, how can I do it? I want to try Pulsar Oxia!

```
version: '3.8'

networks:
  pulsar-oxia:
    driver: bridge
    #ipam:
      #driver: default
      #config:
        #- subnet: 192.168.0.1/24

services:

  ox1:
    container_name: ox1
    hostname: ox1
    ports:
     - "192.168.0.131:6649:6649"
     - "192.168.0.131:6648:6648"
     - "192.168.0.131:8080:8080"
    image: streamnative/oxia:main
    command: >
      bash -c "oxia server --log-json --data-dir=/data/db --wal-dir=/data/wal --db-cache-size-mb=512 --profile && \
               oxia coordinator --log-json --metadata=configmap --profile"
    environment:
      oxia_cluster: test           
    volumes:
      - /data
    networks:
      pulsar-oxia:
        #ipv4_address: 192.168.0.131
      
  
  bk1:
    hostname: bk1
    ports:
      - "192.168.0.131:3181:3181"
      - "192.168.0.131:8003:8000"
    container_name: bk1
    image: apachepulsar/pulsar-all:3.0.0
    command: >
      bash -c "export dbStorage_writeCacheMaxSizeMb="$${dbStorage_writeCacheMaxSizeMb:-16}" && \
               export dbStorage_readAheadCacheMaxSizeMb="$${dbStorage_readAheadCacheMaxSizeMb:-16}" && \
               bin/apply-config-from-env.py conf/bookkeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               # bin/watch-znode.py -z $$zkServers -p /initialized-$$clusterName -w && \
               exec bin/pulsar bookie"
    environment:
      PULSAR_MEM: >
        -Xms128m
        -Xmx256m
        -XX:MaxDirectMemorySize=256m
      PULSAR_GC: >
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=10
        -XX:+ParallelRefProcEnabled
        -XX:+UnlockExperimentalVMOptions
        -XX:+DoEscapeAnalysis
        -XX:ParallelGCThreads=4
        -XX:ConcGCThreads=4
        -XX:G1NewSizePercent=50
        -XX:+DisableExplicitGC
        -XX:-ResizePLAB
        -XX:+ExitOnOutOfMemoryError
        -XX:+PerfDisableSharedMem
      # configure the memory settings based on jvm memory settings
      dbStorage_writeCacheMaxSizeMb: "32"
      dbStorage_readAheadCacheMaxSizeMb: "32"
      dbStorage_rocksDB_writeBufferSizeMB: "8"
      dbStorage_rocksDB_blockCacheSize: "8388608"
      PULSAR_PREFIX_journalDirectories: "/pulsar/data/bookkeeper/journal"
      extraServerComponents: "org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent"
      clusterName: test
      configurationStore: ox1:6649
      numAddWorkerThreads: 8
      useHostNameAsBookieID: "true"
    volumes:
      - ./scripts/apply-config-from-env.py:/pulsar/bin/apply-config-from-env.py:z
    depends_on:
      - ox1
      #- pulsar-init    
    networks:
      pulsar-oxia:
        #ipv4_address: 192.168.0.134

 
```
