### DISCUSSION TITLE
pulsar docker swarm High Availability test

### DISCUSSION THREAD

**Discussion by mingijo-tatum** [apache/pulsar#21040] [Q&A]
I've deployed Pulsar 3.0.0 via docker swarm and I'm posting a question because I'm having issues during high availability testing.
I'm using the following Docker-compose file, and when my working node ec2 goes down, I get the following problem.

```

version: "3"
networks:
  tatum_network:
    name: tatum_network
    driver: overlay
    external: true
services:
  tatum_service_pulsar_zookeeper_1:
    image: pulsar:3.0.0
    user: "${UID}:${GID}"
    hostname: tatum_service_pulsar_zookeeper_1
    networks:
      - tatum_network
    environment:
      - HOSTNAME=tatum_service_pulsar_zookeeper_1
      - ZOOKEEPER_SERVERS=tatum_service_pulsar_zookeeper_1,tatum_service_pulsar_zookeeper_2,tatum_service_pulsar_zookeeper_3
      - metadataStoreUrl=zk:tatum_service_pulsar_zookeeper_1:2181,tatum_service_pulsar_zookeeper_2:2181,tatum_service_pulsar_zookeeper_3:2181
      - PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
             bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
             exec bin/pulsar zookeeper"
    healthcheck:
      test: ["CMD", "bin/pulsar-zookeeper-ruok.sh"]
      interval: 10s
      timeout: 5s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database.enable==true
  tatum_service_pulsar_zookeeper_2:
    image: pulsar:3.0.0
    user: "${UID}:${GID}"
    hostname: tatum_service_pulsar_zookeeper_2
    networks:
      - tatum_network
    environment:
      - HOSTNAME=tatum_service_pulsar_zookeeper_2
      - ZOOKEEPER_SERVERS=tatum_service_pulsar_zookeeper_1,tatum_service_pulsar_zookeeper_2,tatum_service_pulsar_zookeeper_3
      - metadataStoreUrl=zk:tatum_service_pulsar_zookeeper_1:2181,tatum_service_pulsar_zookeeper_2:2181,tatum_service_pulsar_zookeeper_3:2181
      - PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
             bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
             exec bin/pulsar zookeeper"
    healthcheck:
      test: ["CMD", "bin/pulsar-zookeeper-ruok.sh"]
      interval: 10s
      timeout: 5s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database.enable==true
  tatum_service_pulsar_zookeeper_3:
    image: pulsar:3.0.0
    user: "${UID}:${GID}"
    hostname: tatum_service_pulsar_zookeeper_3
    networks:
      - tatum_network
    environment:
      - HOSTNAME=tatum_service_pulsar_zookeeper_3
      - ZOOKEEPER_SERVERS=tatum_service_pulsar_zookeeper_1,tatum_service_pulsar_zookeeper_2,tatum_service_pulsar_zookeeper_3
      - metadataStoreUrl=zk:tatum_service_pulsar_zookeeper_1:2181,tatum_service_pulsar_zookeeper_2:2181,tatum_service_pulsar_zookeeper_3:2181
      - PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
             bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
             exec bin/pulsar zookeeper"
    healthcheck:
      test: ["CMD", "bin/pulsar-zookeeper-ruok.sh"]
      interval: 10s
      timeout: 5s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database.enable==true
```

```

version: "3"
networks:
  tatum_network:
    name: tatum_network
    driver: overlay
    external: true
services:
  tatum_service_pulsar_bookkeeper_1:
    image: pulsar:3.0.0
    user: "${UID}:${GID}"
    networks:
      - tatum_network
    environment:
      - zkServers=tatum_service_pulsar_zookeeper_1:2181,tatum_service_pulsar_zookeeper_2:2181,tatum_service_pulsar_zookeeper_3:2181
      - clusterName=cluster-a
      - BOOKIE_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    volumes:
      - tatum_service_pulsar_bookkeeper1_data:/pulsar/data/bookkeeper
    depends_on:
      - tatum_service_pulsar_init
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database==1
  tatum_service_pulsar_bookkeeper_2:
    image: pulsar:3.0.0
    user: "${UID}:${GID}"
    networks:
      - tatum_network
    environment:
      - zkServers=tatum_service_pulsar_zookeeper_1:2181,tatum_service_pulsar_zookeeper_2:2181,tatum_service_pulsar_zookeeper_3:2181
      - clusterName=cluster-a
      - BOOKIE_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    volumes:
      - tatum_service_pulsar_bookkeeper2_data:/pulsar/data/bookkeeper
    depends_on:
      - tatum_service_pulsar_init
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database==2
volumes:
  tatum_service_pulsar_bookkeeper1_data:
    external: true
  tatum_service_pulsar_bookkeeper2_data:
    external: true
```
![image](https://github.com/apache/pulsar/assets/77369435/45fa8883-9113-4e66-89fa-d59e70b1d0ff)

If one node dies, three zk's are created on the other node, and if you check the logs in the bookkeeper after that, the logs will be infinite as shown in the photo above.

I ask for help how to do it.
