### DISCUSSION TITLE
Error: pulsar chart not found in repo

### DISCUSSION THREAD

**Discussion by ton3r** [apache/pulsar#22396] [Q&A] [answered]
MISSCONFIGURED BY MYSELF!! - solved

I'm trying to install the latest pulsar with the helmchart.
I've overwritten the values.yml as

```yaml
pulsar-spx:
  defaultPulsarImageTag: "3.2.2"
  namespace: "pulsar"
  namespaceCreate: true
  ## Set to true on install
  initialize: true
  labels:
    environment: dev
    customer: apache
    usage: test-environment
  tcpPrefix: "tcp-"  # For Istio this will be "tcp-"
  tlsPrefix: "tls-"  # For Istio this will be "tls-"
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

  components:
    pulsar_manager: true

  monitoring:
    prometheus: true
    grafana: true

  proxy:
    service:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
      loadBalancerIP: 10.164.2.203

  pulsar_manager:
    service:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
      loadBalancerIP: 10.164.2.204
    admin:
      ui_username: "pulsar"
      ui_password: "pulsar007"  # leave empty for random password
      db_username: "pulsar"
      db_password: "pulsar007"  # leave empty for random password

```
But during my Build
`helm dependency build pulsar-ird`
it ends with

_Error: pulsar chart not found in repo https://prometheus-community.github.io/helm-charts_

What am I doing wrong? Thought disabling the prometheus part in the first step would be enough.
