### DISCUSSION TITLE
How to enable server publish time on messages?

### DISCUSSION THREAD

**Discussion by adparts** [apache/pulsar#23073] [Q&A]
Hi all,

The Message class, has the following method:

`Optional<Long> getBrokerPublishTime()`
Get broker publish time from broker entry metadata. 
**Note that only if the feature is enabled in the broker then the value is available.**

Does anyone know how to enable this functionality in the broker? we are not able to find it.

getPublishTime() returns the client timestamp and is not suitable to analyze timings between messages. 

Thank you!

**Comment by lhotari** [comment]
it requires adding this config to `conf/broker.conf`:

```
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendBrokerTimestampMetadataInterceptor
exposingBrokerEntryMetadataToClientEnabled=true
```

For Apache Pulsar Helm chart k8s deployments, this can be actived this way in values.yaml:
```yaml
broker:
  configData:
    PULSAR_PREFIX_brokerEntryMetadataInterceptors: org.apache.pulsar.common.intercept.AppendBrokerTimestampMetadataInterceptor
    PULSAR_PREFIX_exposingBrokerEntryMetadataToClientEnabled: "true"
```
