### DISCUSSION TITLE
Installing a custom sink connector

### DISCUSSION THREAD

**Discussion by filipqlrf** [apache/pulsar#24075] [Q&A] [answered]
What is the best way to add a custom sink connector to the Pulsar instance deployed using the official helm chart? This is the connector I want to use: https://github.com/streamnative/pulsar-io-lakehouse

Once I have the connector available under `/connectors`, it should be easy to setup a sink using that connector and referencing it via
`"archive": "connectors/pulsar-io-lakehouse-{{connector:version}}-cloud.nar"
`

Is there a configuration to do it out of the box, should I use initContainers or something else?

**Comment by lhotari** [comment, marked as answer]
There's a possibility to allow installing directly from an external `https://` url. This is disabled by default [because of security reasons](https://pulsar.apache.org/security/CVE-2024-27894/).

https://github.com/apache/pulsar/blob/4a887217d835629cafb393ddf331441b484d4e2c/conf/functions_worker.yml#L420-L429

For trusted URLs, it's possible to configure `additionalEnabledConnectorUrlPatterns` (for connectors) and `additionalEnabledFunctionsUrlPatterns` (for functions).

In the Apache Pulsar Helm chart, you can set these config values with 
```yaml
broker:
  configData:
    PF_additionalEnabledConnectorUrlPatterns: "https://someurl1/.*,https://someurl2/.*"
    PF_additionalEnabledFunctionsUrlPatterns: "https://someurl1/.*,https://someurl2/.*"
```

in this case this might work so that you could refer the download urls directly, such as `--archive=https://github.com/streamnative/pulsar-io-lakehouse/releases/download/v3.0.10.1/pulsar-io-lakehouse-3.0.10.1.nar`, in the `pulsar-admin sink create` command line.

```yaml
broker:
  configData:
    PF_additionalEnabledConnectorUrlPatterns: "https://github.com/streamnative/pulsar-io-lakehouse/releases/download/.*"
```

I haven't tested this so you might run into issues along the way.
