### DISCUSSION TITLE
JDBC Postgres sink connector error

### DISCUSSION THREAD

**Discussion by Metalmania97** [apache/pulsar#24147] [Q&A]
I encounter a connection error when i produce mqtt messages and the sink connector tries to add them to the postgres db

ERROR org.apache.pulsar.functions.runtime.process.ProcessRuntime - Health check failed for jdbc-postgres-sink-0
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:32947
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused

I use the standalone version of pulsar using docker compose with these jdbc postgres sink configs
```
tenant: "public"
namespace: "default"
name: "jdbc-postgres-sink"
archive: "/pulsar/connectors/pulsar-io-jdbc-postgres-4.0.0.nar"  
className: "org.apache.pulsar.io.jdbc.PostgresJdbcAutoSchemaSink"
inputSpecs:
  persistent://public/default/temp_1:  
    schemaType: JSON
configs:
  userName: "user1"
  password: "1234567890"
  jdbcUrl: "jdbc:postgresql://postgres:5432/mqtt_db"
  tableName: "test"
```
