### DISCUSSION TITLE
Pulsar Docker Compose File

### DISCUSSION THREAD

**Discussion by General-Test** [apache/pulsar#24197] [Q&A]
I am trying to create a pulsar installation on docker , which should have 3 zookeeper, 3 bookies and 2 brokers. I am not sure why this is not working

```
version: '3.8'

services:
  zookeeper-1:
    image: apachepulsar/pulsar:latest
    hostname: zookeeper-1
    container_name: zookeeper-1
    restart: unless-stopped
    environment:
      - PULSAR_MEM=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=512m
      - PULSAR_PREFIX_server.1=zookeeper-1:2888:3888
      - PULSAR_PREFIX_server.2=zookeeper-2:2888:3888
      - PULSAR_PREFIX_server.3=zookeeper-3:2888:3888
      - ZK_myid=1
      - PULSAR_PREFIX_initLimit=10  # Timeout for initial connection
      - PULSAR_PREFIX_syncLimit=5   # Timeout for sync operations
      - PULSAR_PREFIX_4lw.commands.whitelist=*
    command: >
      bash -c "mkdir -p /pulsar/data/zookeeper &&
               echo $${ZK_myid} > /pulsar/data/zookeeper/myid &&
               bin/apply-config-from-env.py conf/zookeeper.conf &&
               bin/generate-zookeeper-config.sh conf/zookeeper.conf &&
               exec bin/pulsar zookeeper"
    volumes:
      - ./data/zookeeper-1:/pulsar/data/zookeeper
    networks:
      - pulsar
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "bin/pulsar-zookeeper-ruok.sh" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  zookeeper-2:
    image: apachepulsar/pulsar:latest
    hostname: zookeeper-2
    container_name: zookeeper-2
    restart: unless-stopped
    environment:
      - PULSAR_MEM=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=512m
      - PULSAR_PREFIX_server.1=zookeeper-1:2888:3888
      - PULSAR_PREFIX_server.2=zookeeper-2:2888:3888
      - PULSAR_PREFIX_server.3=zookeeper-3:2888:3888
      - ZK_myid=2
      - PULSAR_PREFIX_initLimit=10  # Timeout for initial connection
      - PULSAR_PREFIX_syncLimit=5   # Timeout for sync operations
      - PULSAR_PREFIX_4lw.commands.whitelist=*
    command: >
      bash -c "mkdir -p /pulsar/data/zookeeper &&
               echo $${ZK_myid} > /pulsar/data/zookeeper/myid &&
               bin/apply-config-from-env.py conf/zookeeper.conf &&
               bin/generate-zookeeper-config.sh conf/zookeeper.conf &&
               exec bin/pulsar zookeeper"
    volumes:
      - ./data/zookeeper-2:/pulsar/data/zookeeper
    networks:
      - pulsar
    ports:
      - "2182:2181"
    depends_on:
      zookeeper-1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "bin/pulsar-zookeeper-ruok.sh" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  zookeeper-3:
    image: apachepulsar/pulsar:latest
    hostname: zookeeper-3
    container_name: zookeeper-3
    restart: unless-stopped
    environment:
      - PULSAR_MEM=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=512m
      - PULSAR_PREFIX_server.1=zookeeper-1:2888:3888
      - PULSAR_PREFIX_server.2=zookeeper-2:2888:3888
      - PULSAR_PREFIX_server.3=zookeeper-3:2888:3888
      - ZK_myid=3
      - PULSAR_PREFIX_initLimit=10
      - PULSAR_PREFIX_syncLimit=5
      - PULSAR_PREFIX_4lw.commands.whitelist=*
    command: >
      bash -c "mkdir -p /pulsar/data/zookeeper &&
               echo $${ZK_myid} > /pulsar/data/zookeeper/myid &&
               bin/apply-config-from-env.py conf/zookeeper.conf &&
               bin/generate-zookeeper-config.sh conf/zookeeper.conf &&
               exec bin/pulsar zookeeper"
    volumes:
      - ./data/zookeeper-3:/pulsar/data/zookeeper
    networks:
      - pulsar
    ports:
      - "2183:2181"
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "bin/pulsar-zookeeper-ruok.sh" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  pulsar-init-metadata:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-init-metadata
    environment:
      - PULSAR_PREFIX_metadataServiceUri=zk://zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/ledgers
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    networks:
      - pulsar
    command: >
      bash -c "bin/pulsar initialize-cluster-metadata --cluster cluster-a --zookeeper zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 --configuration-store zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 --web-service-url http://broker-1:8080 --broker-service-url pulsar://broker-1:6650"

  pulsar-init-bookkeeper:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-init-bookkeeper
    environment:
      - PULSAR_PREFIX_zkServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_metadataServiceUri=zk://zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/ledgers
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
      pulsar-init-metadata:
        condition: service_completed_successfully
    networks:
      - pulsar
    command: >
      bash -c "
        bin/apply-config-from-env.py conf/bookkeeper.conf &&
                bin/bookkeeper shell nukeexistingcluster --zkledgersrootpath /ledgers --force &&
                bin/bookkeeper shell initnewcluster
      "

  bookie-1:
    image: apachepulsar/pulsar:latest
    container_name: bookie-1
    restart: on-failure
    environment:
      - PULSAR_PREFIX_clusterName=cluster-a
      - PULSAR_PREFIX_bookieId=bookie1
      - PULSAR_PREFIX_zkServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_metadataServiceUri=zk://zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/ledgers
      - PULSAR_PREFIX_advertisedAddress=bookie-1
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
      pulsar-init-bookkeeper:
        condition: service_completed_successfully
    volumes:
      - ./data/bookie-1:/pulsar/data/bookkeeper
    networks:
      - pulsar
    command: >
      bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    healthcheck:
      test: [ "CMD", "bin/bookkeeper", "shell", "bookiesanity" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m

  bookie-2:
    image: apachepulsar/pulsar:latest
    container_name: bookie-2
    restart: on-failure
    environment:
      - PULSAR_PREFIX_clusterName=cluster-a
      - PULSAR_PREFIX_bookieId=bookie2
      - PULSAR_PREFIX_zkServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_metadataServiceUri=zk://zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/ledgers
      - PULSAR_PREFIX_advertisedAddress=bookie-2
      - PULSAR_PREFIX_PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
      pulsar-init-bookkeeper:
        condition: service_completed_successfully
    volumes:
      - ./data/bookie-2:/pulsar/data/bookkeeper
    networks:
      - pulsar
    command: >
      bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    healthcheck:
      test: [ "CMD", "bin/bookkeeper", "shell", "bookiesanity" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m

  bookie-3:
    image: apachepulsar/pulsar:latest
    container_name: bookie-3
    restart: on-failure
    environment:
      - PULSAR_PREFIX_clusterName=cluster-a
      - PULSAR_PREFIX_bookieId=bookie3
      - PULSAR_PREFIX_zkServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_metadataServiceUri=zk://zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/ledgers
      - PULSAR_PREFIX_advertisedAddress=bookie-3
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
      pulsar-init-bookkeeper:
        condition: service_completed_successfully
    volumes:
      - ./data/bookie-3:/pulsar/data/bookkeeper
    networks:
      - pulsar
    command: >
      bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    healthcheck:
      test: [ "CMD", "bin/bookkeeper", "shell", "bookiesanity" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m

  broker-1:
    image: apachepulsar/pulsar:latest
    container_name: broker-1
    restart: on-failure
    environment:
      - PULSAR_PREFIX_clusterName=cluster-a
      - PULSAR_PREFIX_zookeeperServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_configurationStoreServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_managedLedgerDefaultEnsembleSize=1
      - PULSAR_PREFIX_managedLedgerDefaultWriteQuorum=1
      - PULSAR_PREFIX_managedLedgerDefaultAckQuorum=1
      - PULSAR_PREFIX_advertisedAddress=broker-1
      - PULSAR_PREFIX_advertisedListeners=external:pulsar://broker-1:6650
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    depends_on:
      bookie-1:
        condition: service_healthy
      bookie-2:
        condition: service_healthy
      bookie-3:
        condition: service_healthy
    ports:
      - "6650:6650"
      - "8080:8080"
    command: >
      bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    networks:
      - pulsar
    healthcheck:
      test: [ "CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 30
      start_period: 1m

  broker-2:
    image: apachepulsar/pulsar:latest
    container_name: broker-2
    restart: on-failure
    environment:
      - PULSAR_PREFIX_clusterName=cluster-a
      - PULSAR_PREFIX_zookeeperServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_configurationStoreServers=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      - PULSAR_PREFIX_managedLedgerDefaultEnsembleSize=1
      - PULSAR_PREFIX_managedLedgerDefaultWriteQuorum=1
      - PULSAR_PREFIX_managedLedgerDefaultAckQuorum=1
      - PULSAR_PREFIX_advertisedAddress=broker-2
      - PULSAR_PREFIX_advertisedListeners=external:pulsar://broker-2:6650
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    depends_on:
      bookie-1:
        condition: service_healthy
      bookie-2:
        condition: service_healthy
      bookie-3:
        condition: service_healthy
    ports:
      - "6651:6650"
      - "8081:8080"
    command: >
      bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    networks:
      - pulsar
    healthcheck:
      test: [ "CMD", "bin/pulsar-admin", "brokers", "healthcheck" ]
      interval: 30s
      timeout: 5s
      retries: 30
      start_period: 1m

  pulsar-init:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-init
    restart: on-failure
    entrypoint: >
      bash -c "
        sleep 30 && \
        bin/pulsar-admin clusters create cluster-a --url http://broker-1:8080 --broker-url pulsar://broker-1:6650 && \
        bin/pulsar-admin tenants create tenant-a && \
        bin/pulsar-admin namespaces create tenant-a/namespace-a && \
        bin/pulsar-admin topics create tenant-a/namespace-a/topic-a
      "
    depends_on:
      broker-1:
        condition: service_healthy
      broker-2:
        condition: service_healthy
    networks:
      - pulsar

networks:
  pulsar:
    driver: bridge

```
