### DISCUSSION TITLE
pulsar IO sink missing after functions worker cluster leader restart

### DISCUSSION THREAD

**Discussion by bohuslav-broza** [apache/pulsar#24202] [Q&A]
hi everyone,
for years we are using Apache Pulsar deployed to K8s and at the moment we are running the version 3.3.5. Lately we extended our Pulsar usage with a Pulsar IO sink. We are dumping data from a topic to an AWS S3 using the [cloud storage sink connector](https://github.com/streamnative/pulsar-io-cloud-storage) version 3.3.5.2 and for pulsar resource management we use [pulsar resource operator](https://github.com/streamnative/pulsar-resources-operator) version 0.9.2. 

**With our configuration we run into situations, where after  restart of the functions worker cluster leader the sink stops operate. Details follows. Any help, hint or suggestion is highly appreciated.** 

Our cluster consists of two brokers and the functions workers are configured to run on those brokers with kubernetess runtime for the function instance
Functions workers form a cluster and typically broker-1 is the leader

```
pulsarctl functions-worker get-cluster 
[
  {
    "workerId": "c-pulsar-fw-pulsar-broker-0.pulsar-broker.pulsar.svc.cluster.local-8080",
    "workerHostname": "pulsar-broker-0.pulsar-broker.pulsar.svc.cluster.local",
    "port": 8080
  },
  {
    "workerId": "c-pulsar-fw-pulsar-broker-1.pulsar-broker.pulsar.svc.cluster.local-8080",
    "workerHostname": "pulsar-broker-1.pulsar-broker.pulsar.svc.cluster.local",
    "port": 8080
  }
]

pulsarctl functions-worker get-cluster-leader
{
  "workerId": "c-pulsar-fw-pulsar-broker-1.pulsar-broker.pulsar.svc.cluster.local-8080",
  "workerHostname": "pulsar-broker-1.pulsar-broker.pulsar.svc.cluster.local",
  "port": 8080
}
```

The sink is created using the pulsar resource operator

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarSink
metadata:
  name: testsink
  namespace: auditlog
spec:
  className: org.apache.pulsar.io.jcloud.sink.CloudStorageGenericRecordSink
  cleanupSubscription: true
  connectionRef:
    name: "pulsar-connection"
  customRuntimeOptions:
    jobNamespace: "auditlog"
    resourceRequirements:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "384Mi"
        cpu: "500m"
  inputs:
    - persistent://auditlog/default/testsink
  archive:
    url: builtin://cloud-storage
  tenant: auditlog
  namespace: default
  name: testsink
  sourceSubscriptionName: auditlog-sub-testsink
  parallelism: 1
  sourceSubscriptionPosition: Earliest
  configs:
    provider: "s3v2"
    useDefaultCredentials: "true"
    bucket: "bobrpulsar-testing123"
    region: "us-east-1"
    formatType: "json"
    partitionerType: "PARTITION"
    batchSize: "10000"
    batchTimeMs: "300000"
```

The sink pod pf-auditlog-default-testsink-0 is created correctly in the auditlog k8s namespce and all the required K8s object - sts and service. The sink is assigned to the broker-0 

```
 pulsarctl functions-worker get-function-assignments
{
  "c-pulsar-fw-pulsar-broker-0.pulsar-broker.pulsar.svc.cluster.local-8080": [
    "auditlog/default/testsink:-1"
  ]
}
```

When we restart the broker-0 the sink continues to work, however if we restart the leader of the functions worker cluster the broker-0 deletes the sink function (all the K8s objects) after the broker-1 becomes the leader again and we end up in the situation, where there is no pod running with the sink function

```
pulsarctl functions-worker get-function-assignments
{}
```

However the operator itself thinks the sink is running fine.

```
 k get pulsarsink -n auditlog
NAME              RESOURCE_NAME     GENERATION   OBSERVED_GENERATION   READY
testsink          testsink          18           18                    True
```

Functions worker configuration
[broker-1-functions_worker.txt](https://github.com/user-attachments/files/19863836/broker-1-functions_worker.txt)
[broker-0-functions_worker.txt](https://github.com/user-attachments/files/19863840/broker-0-functions_worker.txt)

The expected behaviour I require is that during the functions worker cluster changes, which are often in the K8s environment as pods are rescheduled or fail, the sink would survive these events and continue to operate. Any help, hint or suggestion is appreciated.
