### DISCUSSION TITLE
pulsar_cluster log will fill up the disk

### DISCUSSION THREAD

**Discussion by 1275718633** [apache/pulsar#24334] [Q&A]
The log space in the "ledgers/current" directory under the journalDirectory path configured in bookkeepr is too large and is about to fill up the disk. How should I handle this?

**Comment by lhotari** [comment]
This is a good question. Some quick hints to prevent this from happening:
* read https://pulsar.apache.org/docs/4.0.x/cookbooks-retention-expiry/ to understand the basics
* Pulsar will retain message backlogs on subscriptions, so you will need to monitor backlog sizes or set policies to prevent disk space over use
  * storage metrics at namespace or topic level: https://pulsar.apache.org/docs/4.0.x/reference-metrics/#topic-metrics

Some useful details to be aware of:
* Only fully consumed (no subscription and no other retention) ledgers for a topic can be removed
* BookKeeper won't release data from deleted ledgers until there's a BookKeeper garbage collection cycle
  * [Garbage collection settings](https://bookkeeper.apache.org/docs/reference/config#garbage-collection-settings)

For test environments, you can use use these settings for more aggressive disk cleanup
```yaml
bookkeeper:
  configData:
    # more aggressive disk cleanup
    journalMaxSizeMB: "256"
    majorCompactionInterval: "600"
    minorCompactionInterval: "300"
    compactionRateByEntries: "5000"
    gcWaitTime: "60000"

broker:
  configData:
    # more aggressive disk cleanup
    managedLedgerMinLedgerRolloverTimeMinutes: "1"
    managedLedgerMaxLedgerRolloverTimeMinutes: "5"
```
