### ISSUE TITLE
[docs] Log4j configuration needs to be better documented

### ISSUE THREAD

**Issue by devinbost** [apache/pulsar#10200]
We currently don't have much documentation around how to configure Log4j debugging for Pulsar, and the log4j docs are confusing. For example, I'm trying to enable DEBUG logging for Pulsar, but we're having trouble getting debug statements to show up in our rolling log. The Pulsar docs don't provide sufficient explanation around how to do this.

**Comment by devinbost** [comment]
For example, the following Log4j file doesn't emit debug statements for permits from `ConsumerImpl`, `Consumer`, or `PersistentDispatcherMultipleConsumers`

[log4j2.yaml.txt](https://github.com/apache/pulsar/files/6299567/log4j2.yaml.txt)

**Comment by devinbost** [comment]
I tried hard-coding `"debug"` in place of `"${sys:pulsar.log.level}"` in this part of the file:
```
Root:
      level: debug
      additivity: true
      AppenderRef:
        - ref: "${sys:pulsar.log.appender}"
          level: "${sys:pulsar.log.level}"
        - ref: Prometheus
          level: info
```
but the only classes that appear to be emitting debug-level information are bookkeeper classes.

**Comment by devinbost** [comment]
I was able to get debug statements after hard coding `"debug"` in place of `"${sys:pulsar.log.level}"` in this part of the log4j2.yaml file:
```
Root:
      level: debug
      additivity: true
      AppenderRef:
        - ref: "${sys:pulsar.log.appender}"
          level: "${sys:pulsar.log.level}"
        - ref: Prometheus
          level: info
```
However, I haven't been able to get debug logging on the functions.
