### ISSUE TITLE
Failed to create consumer while using proxy and `Prefix` Subscription Authentication Mode

### ISSUE THREAD

**Issue by dragonls** [apache/pulsar#10221]
**Describe the bug**
I am using pulsar cluster on k8s, deployed by `pulsar-helm-chart`, having `proxy` component and using JWT for authentication.
If one namespace change the subscription authentication mode from `None` to `Prefix`, the consume can not subscribe the topic even having the valid role prefix.

**To Reproduce**
1. Using pulsar cluster on k8s, having `proxy` component and using JWT for authentication
2. Set the subscription authentication mode of one namespace from `None` to `Prefix`, e.g. namespace `test/auth`
3. Add a subscription `roleA-test` of topic `persistent://test/auth/topic`
3. Use role `roleA` to consume the topic `persistent://test/auth/topic`

**Expected behavior**
The consumer should subscribe and consume the topic normally.

**Screenshots**
The consumer get the error `org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: Failed to subscribe ...`
![image](https://user-images.githubusercontent.com/2565118/114648477-7782d580-9d11-11eb-9c34-0994a915763d.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
The auth part of helm chart values:
```yaml
auth:
  authentication:
    enabled: true
    provider: "jwt"
    jwt:
      # Enable JWT authentication
      # If the token is generated by a secret key, set the usingSecretKey as true.
      # If the token is generated by a private key, set the usingSecretKey as false.
      usingSecretKey: true
  authorization:
    enabled: true
  superUsers:
    # broker to broker communication
    broker: "broker-admin"
    # proxy to broker communication
    proxy: "proxy-admin"
    # pulsar-admin client to broker/proxy communication
    client: "admin"
```

The broker log:
```
20:31:48.269 [pulsar-io-25-4] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /9.165.129.25:52986
20:31:48.281 [pulsar-io-25-4] INFO  org.apache.pulsar.broker.service.ServerCnx - [/9.165.129.25:52986] org.apache.pulsar.broker.PulsarServerException: Failed to create consumer - The subscription name needs to be prefixed by the authentication role, like proxy-admin-xxxx for topic: persistent://test/auth/p1-partition-0 with role roleA
```
