### ISSUE TITLE
Topic auto creation won't create partitioned topics if client connects to proxy.

### ISSUE THREAD

**Issue by yangou** [apache/pulsar#10449]
**Describe the bug**

Configured the namespace to enable topic auto-creation,  with partitioned topic type by default. 
If your consumer/producer are directly connected to broker, your topic will be created corrected with default number of partitions.
If your consumer/producer are connected through the pulsar proxy, discovery node, then the topic is created as none-partitioned one.

**To Reproduce**
1. Setup your pulsar cluster with proxy in front of your brokers.
2. Create a new namespace with the below configuration:

```
autoTopicCreationOverride:
  allowAutoTopicCreation: true
  topicType: partitioned
  defaultNumPartitions: 16
autoSubscriptionCreationOverride:
  allowAutoSubscriptionCreation: true
```

3. Use either java/go client to connect to pulsar proxy. Produce a message to an non-exist topic of that namespace.

**Expected behavior**
A new topic created with 16 parititons
