### ISSUE TITLE
[sink jdbc-clickhouse] avro (and possibly others) sink is broken

### ISSUE THREAD

**Issue by smazurov** [apache/pulsar#11457]
**Describe the bug**

When publishing & consuming messages avro & json schema encoding works as expected. After creating a simple clickhouse sink (using config from the docs), the messages get written to the table, but every value is `null`, making it useless. Downgrading to 2.7.2 and re-running the test, with no avro or db schema changes or sink config works as expected. 

**To Reproduce**
1. Start up a clickhouse and pulsar-standalone
1. Create a clickhouse sink attached to the test topic
2. Publish some messages with avro schema

**Expected behavior**

I expect the sink to correctly populate my fields.

**Comment by Lucgarg** [comment]
I think the problem is that to enter data in JSON format, you have to specify the clickhouse type of JSONEachRow format. But i think the jdbc connector doesn't give that option.

**Comment by smazurov** [comment]
I'm assuming it has to do with the way schemas are handled regardless of destination, [here's another issue](https://github.com/apache/pulsar-client-go/issues/546) that makes it seem specific to golang & sql

**Comment by codelipenghui** [comment]
The issue had no activity for 30 days, mark with Stale label.

**Comment by smazurov** [comment]
The PR mentioned in linked issue deals with this downstream, but I do not know if underlying issue has been fixed.

**Comment by estebanz01** [comment]
I'm seeing a similar issue but without schema on pulsar 3.1 and JDBC Clickhouse sink with `pulsar-io-jdbc-clickhouse-3.1.1.nar` NAR file.

Here's my config:
```yaml
configs:
  userName: "default"
  password: "default"
  jdbcUrl: "jdbc:clickhouse://localhost:8123/iot"
  tableName: "pulsar_data"
  useTransactions: "false"
  nonKey: "device_name, data_content, device_properties, datetime_info, topicName"
```
