### ISSUE TITLE
Pulsar Sink Localrun - Not able to find table - PostgreSQL

### ISSUE THREAD

**Issue by picassoo** [apache/pulsar#11568]
**Sink Connectors can not find table**
Hi,

I tried  Pulsar IO features (source and sink connectors) in standalone mode.  Source connectors works very well with debezium connector. But Sink Connector can not find table while deploying jdbc postgresql connector. Naturally , Pulsar can not write topic message to table. 
Sink Config YAML File:

```
tenant: "public"
namespace: "default"
name: "postgresql-storage-sink"
archive: "connectors/pulsar-io-jdbc-postgres-2.8.0.nar"
parallelism: 1
inputs: 
- "user-avro-topic"
configs:
  userName: "stream"
  password: "password"
  jdbcUrl: `"jdbc:postgresql://postgreshost:5432/postgres?currentSchema=public"`
  tableName: "pulsarsink"
```

**Possible Solution**

I suspected jdbcUrl can be wrong. I excanged host, database and schema sequentially. When I did these, Pulsar throws connection exception.
Eventually, problem is not caused from jdbcUrl. But I never seen any example on pulsar site demostrate sink connector with database schema info.
Can you give any example that accomplish to connect postgresql with db schema info?

Pulsar version   2.8.0 
Docker version 20.10.7
postgres (PostgreSQL) 13.3 

**Pictures**

![table](https://user-images.githubusercontent.com/12486621/128337759-99f3834b-eb17-4051-b757-d2e151cae7d9.png)
![cmd](https://user-images.githubusercontent.com/12486621/128337766-b5dd1346-f85b-403b-8866-04e33adfbdd6.png)
