### ISSUE TITLE
[Doc] JSON configuration of connector

### ISSUE THREAD

**Issue by Anonymitaet** [apache/pulsar#12768]
Here is a doc issue from @merlimat :

>>>>>>

I think there’s a problem in most pulsar-io examples with respect to the JSON configuration specific to each connector.
For example in https://pulsar.apache.org/docs/en/io-quickstart/#configure-a-cassandra-sink we have

```
{
    "roots": "localhost:9042",
    "keyspace": "pulsar_test_keyspace",
    "columnFamily": "pulsar_test_table",
    "keyname": "key",
    "columnName": "col"
}
```
The corresponding YAML example is:
```
configs:
    roots: "localhost:9042"
    keyspace: "pulsar_test_keyspace"
    columnFamily: "pulsar_test_table"
    keyname: "key"
    columnName: "col"
```
The JSON fails to submit because the fields are compared to the Pulsar-IO basic configs and not the connector-specific configs.
The correct JSON should be:
```
{
    "configs" : {
        "roots": "localhost:9042",
        "keyspace": "pulsar_test_keyspace",
        "columnFamily": "pulsar_test_table",
        "keyname": "key",
        "columnName": "col"
    }
}
```

Can anyone help resolve this doc issue? Thanks!
