### ISSUE TITLE
[Monitoring - Broker] - Need a metric to track how many consumers are connected and consuming from a given subscription

### ISSUE THREAD

**Issue by NadirJ** [apache/pulsar#15032]
**Description**
I'm monitoring Pulsar and I would like the ability to monitor how many consumers are connected and subscribing from a given subscription.

Right now this metric already exists for topics`pulsar_consumers_count`
 
It tells how many consumers are connected to a given topic/partition.

I would like a similar metric for subscriptions, i.e `pulsar_subscription_consumers_count`

Specifically, I'm trying to detect a "Stuck" Subscriptions and alert on this case when it occurs

Here is the sample prometheus alerting rule I need
  ```
- name: stuck-subscription
      rules:
      - alert: StuckParitionOrTopic
        expr: pulsar_subscription_back_log > 0 and pulsar_subscription_msg_rate_out == 0 and pulsar_subscription_consumers_count > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: Subscription for {{ $labels.topic }} appears to be stuck.
          identifier: '{{ $labels.topic }}' 
```
