### ISSUE TITLE
Don't show logs from the pulsar client of Java

### ISSUE THREAD

**Issue by jiahaoc1993** [apache/pulsar#15158]
**Is your enhancement request related to a problem? Please describe.**
The pulsar client instance writes tons of logs to my logger, which is messing up our critical business logs. I would like to strip the pulsar relevant log from the logger.

**Describe the solution you'd like**
Add a parameter to the constructor of the pulsar client, and let the user decides where to write logs.

**Comment by BewareMyPower** [comment]
There is no need to add a parameter, Pulsar client uses [SLF4J](https://www.slf4j.org/) as its logger. You can choose an any SLF4J compatible logging framework.

For example, I import `slf4j-simple` as the runtime dependency.
```xml
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.7.30</version>
      <scope>runtime</scope>
    </dependency>
```

Then I add a `simplelogger.properties` to retain only warn and error level logs.

```properties
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss:SSS%  
```

In production, I think you can choose a more flexible logging framework like `slf4j-log4j2` and customize your logger configuration file to specify the log path.

**Comment by jiahaoc1993** [comment]
@BewareMyPower  Thanks for the reply. Actually, I am using SLF4j on log4j, but how could I redirect all pulsar client relevant logs to /dev/null while remaining others without changes ;).

**Comment by BewareMyPower** [comment]
It's an issue about log4j configuration, you'd better learn more from the [log4j documentation](https://logging.apache.org/log4j/2.x/manual/configuration.html).

```yaml
    Logger:
      # TODO: specify the package name of pulsar-client, log level and appender
      - name: org.apache.pulsar.client
        level: warn
        additivity: false
        AppenderRef:
          - ref: Console
```
