### ISSUE TITLE
[Docker] - Unable to mount /pulsar/data in the 2.10.0 image version

### ISSUE THREAD

**Issue by M1loseph** [apache/pulsar#15230]
**Describe the bug**

I'm unable to mount pulsar/data volume. In the newest image the user is changed to UID 10000. Since all volumes mounted by docker belong to root user and group, pulsar can't write to it and exits with an exception.

**To Reproduce**
1. Create docker-compose.yml file

```yml
version: '3.7'
services:
  pulsar:
    image: apachepulsar/pulsar:2.10.0
    ports:
      - "8080:8080"
      - "6650:6650"
    volumes:
      - "pulsar-volume:/pulsar/data"
    entrypoint: ["bin/pulsar", "standalone"]
volumes:
  pulsar-volume:
```

2. Run it with `docker-compose up`
3. Container will exit because of an exception

**Expected behavior**
Container should have started.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
