### ISSUE TITLE
[Bug] API /admin/persistent/ return 405 Method Not Allowed

### ISSUE THREAD

**Issue by ywave620** [apache/pulsar#19459]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.9.0

### Minimal reproduce step

start pulsur through a docker-compose.yml
```yml
version: "3"

services:
  pulsur:
    container_name: test-pulsur
    image: apachepulsar/pulsar:2.9.0
    entrypoint: [ "bin/pulsar", "standalone" ]
    ports:
        - 2003:8080
    networks:
      - test
 
networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 173.20.0.0/16
```

then 
```sh
curl 127.0.0.1:2003/admin/persistent/test/rogertyang/tap/partitions?checkAllowAutoCreation=true 
```

### What did you expect to see?

200 of course

### What did you see instead?

output from container
```
test-pulsur  | 2023-02-08T07:59:38,005+0000 [pulsar-web-59-3] INFO  org.eclipse.jetty.server.RequestLog - 173.20.0.1 - - [08/Feb/2023:07:59:37 +0000] "GET /admin/persistent/test/rogertyang/tap/partitions?checkAllowAutoCreation=true HTTP/1.1" 405 176 "-" "Pulsar-httpClient-Go-v2" 10
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
