### ISSUE TITLE
[Bug] ETCD doesn't work as a metadata store.

### ISSUE THREAD

**Issue by MeydanOzeri** [apache/pulsar#22028]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

docker image: apachepulsar/pulsar-all:3.1.2

### Minimal reproduce step

1. Deploy an etcd cluster in kubernetes.
2. deploy bookkeeper using these yamls:

Headless service
```
apiVersion: v1
kind: Service
metadata:
    name: bookkeeper-headless
    namespace: pulsar
spec:
    clusterIP: None
    selector:
        app: bookkeeper
    publishNotReadyAddresses: true
    ports:
        - name: bookie
          port: 3181
          targetPort: 3181
        - name: admin
          port: 8080
          targetPort: 8080
```

Stateful set
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: bookkeeper
    namespace: pulsar
spec:
    serviceName: bookkeeper-headless
    replicas: 3
    selector:
        matchLabels:
            app: bookkeeper
    volumeClaimTemplates:
        - metadata:
              name: journal-data
          spec:
              storageClassName: fast
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 100Gi
        - metadata:
              name: ledger-data
          spec:
              storageClassName: fast
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 100Gi
    template:
        metadata:
            labels:
                app: bookkeeper
        spec:
            containers:
                - name: bookie
                  image: apachepulsar/pulsar-all:3.1.2
                  command:
                      - bash
                      - -c
                      - bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie
                  volumeMounts:
                      - name: journal-data
                        mountPath: /data/bookkeeper/journal
                      - name: ledger-data
                        mountPath: /data/bookkeeper/ledgers
                  env:
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                apiVersion: v1
                                fieldPath: metadata.name
                      - name: advertisedAddress
                        value: $(POD_NAME).bookie-headless.pulsar.svc.cluster.local
                      - name: httpServerEnabled
                        value: 'true'
                      - name: useHostNameAsBookieID
                        value: 'true'
                      - name: allowStorageExpansion
                        value: 'true'
                      - name: metadataServiceUri
                        value: metadata-store:etcd://http://etcd-0.etcd-headless.pulsar.svc.cluster.local:2379,http://etcd-1.etcd-headless.pulsar.svc.cluster.local:2379,http://etcd-2.etcd-headless.pulsar.svc.cluster.local:2379
                  resources:
                      requests:
                          cpu: '2'
                          memory: '2Gi'
                      limits:
                          cpu: '4'
                          memory: '5Gi'
                  ports:
                      - containerPort: 8080
                        name: admin
                      - containerPort: 3181
                        name: bookie
                  readinessProbe:
                      httpGet:
                          path: '/heartbeat'
                          port: admin
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      failureThreshold: 10
                  livenessProbe:
                      httpGet:
                          path: '/heartbeat'
                          port: admin
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      failureThreshold: 10
```

### What did you expect to see?

A working bookkeeper deployment that uses etcd.

### What did you see instead?

these logs:

`2024-02-05T21:03:19,462+0000 [vert.x-eventloop-thread-0] WARN  io.netty.bootstrap.Bootstrap - Unknown channel option 'io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT' for channel '[id: 0x43302b71]'`

`2024-02-05T21:03:21,402+0000 [metadata-store-etcd-session-watcher-3-1] WARN  org.apache.pulsar.metadata.impl.EtcdSessionWatcher - Etcd client is disconnected. Waiting to reconnect, time remaining = 10.991 seconds`

`2024-02-05T21:03:33,408+0000 [metadata-store-etcd-session-watcher-3-1] ERROR org.apache.pulsar.metadata.impl.EtcdSessionWatcher - Etcd lease keep-alive timeout. Notifying session is lost.`

these logs repeat and the bookkeeper is not working.

### Anything else?

The etcd cluster is working fine and can be accessed from the bookkeeper pod if i exec into it.
