### ISSUE TITLE
[Bug] /metrics endpoint processes requests one-by-one and seems to queue up waiting requests infinitely, ignoring the request timeout

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#22477]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Applies to at least 3.0.x and 3.2.x versions of the Broker.

### Minimal reproduce step

TBD. I believe this could be done with a http performance testing tool such as k6 or wrk2. Will follow up later. This might also require a large amount of topics so that the metrics size is significant.

This problem reproduces also with the `metricsBufferResponse=true` setting which is expected to cache the results and allow concurrent requests.

### What did you expect to see?

Calling the /metrics endpoint should be possible concurrently and should generate the metrics results once and share it across the concurrent requests. The expiration of the cached result should be configurable.

### What did you see instead?

requests queue up until there there's a failure about reaching the connection limit 
`INFO org.eclipse.jetty.server.ConnectionLimit - Connection Limit(2048) reached for [ServerConnector@.........{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}]`

### Anything else?

The problem is partially mitigated by enabling Gzip compression with #21667, however it doesn't address the root cause.
There has been a previous attempt to address performance problems in the `/metrics` endpoint with #14453.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by lhotari** [comment]
In the above case, I noticed that the default scraping interval was 10 seconds for Prometheus in the Apache Pulsar Helm chart. It's possible that the scraping was part of how the broker got into a bad state and the metrics response is empty. It confirms that the current solution has multiple issue.

**Comment by lhotari** [comment]
With the topics created with `java -cp build/libs/pulsar-playground-all.jar com.github.lhotari.pulsar.playground.TestScenarioCreateLongNamedTopics`, this `/metrics/` empty response issue reproduces consistently.
After a broker restart, the problem starts happening after triggering loading of all topics with `java -cp build/libs/pulsar-playground-all.jar com.github.lhotari.pulsar.playground.TestScenarioLoadAll`

**Comment by lhotari** [comment]
Ran out of heap in the test, trying with more heap:
```yaml
components:
  proxy: false
affinity:
  anti_affinity: false
bookkeeper:
  resources:
    requests:
      memory: 800m
      cpu: 1
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx400m -XX:MaxDirectMemorySize=300m
broker:
  replicaCount: 1
  resources:
    requests:
      memory: 2500m
      cpu: 1
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx1024m -XX:MaxDirectMemorySize=1024m
```
