### ISSUE TITLE
pulsar manager init Failed to connect to pulsar-pulsar-manager port 9527

### ISSUE THREAD

**Issue by erictarrence** [apache/pulsar#23444]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

pulsar version: 3.3.2
kubernetes version:1.30.0
pulsar auth mode:JWT

### Minimal reproduce step

[pulsar-3.3.2-values.txt](https://github.com/user-attachments/files/17349424/pulsar-3.3.2-values.txt)
git clone https://github.com/apache/pulsar-helm-chart
cd pulsar-helm-chart
kubectl create ns pulsar
./scripts/pulsar/prepare_helm_release.sh -n <k8s-namespace> -k <helm-release-name>

helm repo add apache https://pulsar.apache.org/charts
helm repo update
Install pulsar using the attached Helm values.yaml to reproduce the failure

### What did you expect to see?

I hope that the pulsar-pulsar-manager-init pod is in the Completed status and can access  pulsar-pulsar-manager port 9527 normally

### What did you see instead?

pulsar-pulsar-manager-init pod is still CrashLoopBackOff status,can;t connect   pulsar-pulsar-manager port 9527

```
kubectl -n pulsar logs pulsar-pulsar-manager-init-7wc46
Defaulted container "pulsar-pulsar-manager-init" out of: pulsar-pulsar-manager-init, wait-pulsar-manager-ready (init), wait-broker-ready (init)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    36  100    36    0     0   6384      0 --:--:-- --:--:-- --:--:--  7200
*   Trying 172.23.5.73:9527...
* connect to 172.23.5.73 port 9527 failed: Connection refused
* Failed to connect to pulsar-pulsar-manager port 9527 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to pulsar-pulsar-manager port 9527 after 0 ms: Connection refused

creating account
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.23.7.176:7750...
* Connected to pulsar-pulsar-manager-admin (172.23.7.176) port 7750 (#0)
> PUT /pulsar-manager/users/superuser HTTP/1.1
> Host: pulsar-pulsar-manager-admin:7750
> User-Agent: curl/7.81.0
> Accept: */*
> X-XSRF-TOKEN: 1ac24f81-d5b2-4daa-a804-c7b9dc427420
> Cookie: XSRF-TOKEN=1ac24f81-d5b2-4daa-a804-c7b9dc427420;
> Content-Type: application/json
> Content-Length: 115
> 
} [115 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Sat, 12 Oct 2024 08:18:00 GMT
< Connection: close
< 
{ [1190 bytes data]
100  1298    0  1183  100   115  85619   8323 --:--:-- --:--:-- --:--:-- 99846
* Closing connection 0
*   Trying 172.23.5.73:9527...
* connect to 172.23.5.73 port 9527 failed: Connection refused
* Failed to connect to pulsar-pulsar-manager port 9527 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to pulsar-pulsar-manager port 9527 after 0 ms: Connection refused
{"timestamp":"2024-10-12T08:18:01.009+0000","status":500,"error":"Internal Server Error","message":"\n### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \"users_name_key\"\n  Detail: Key (name)=(pulsar) already exists.\n### The error may exist in org/apache/pulsar/manager/mapper/UsersMapper.java (best guess)\n### The error may involve org.apache.pulsar.manager.mapper.UsersMapper.save-Inline\n### The error occurred while setting parameters\n### SQL: INSERT INTO users (access_token, name, description, email, phone_number, location, company, expire, password)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)\n### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \"users_name_key\"\n  Detail: Key (name)=(pulsar) already exists.\n; ]; ERROR: duplicate key value violates unique constraint \"users_name_key\"\n  Detail: Key (name)=(pulsar) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \"users_name_key\"\n  Detail: Key (name)=(pulsar) already exists.","path":"/pulsar-manager/users/superuser"}
{ "name": "pulsar", "broker": "http://pulsar-broker:8080", "bookie": "http://pulsar-bookie:8000"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.23.5.73:9527...
* connect to 172.23.5.73 port 9527 failed: Connection refused
* Failed to connect to pulsar-pulsar-manager port 9527 after 3 ms: Connection refused
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to pulsar-pulsar-manager port 9527 after 3 ms: Connection refused
```
pulsar_manager configuration is as follows:

```
pulsar_manager: 
  replicaCount: 1
  nodeSelector:
    ceph-rbd-plug: enabled
  tolerations:
  - effect: NoExecute
    key: ceph-taint
    operator: Equal
    value: osd
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    data:
      name: data
      size: 128Mi
      storageClassName: rook-ceph-block
  configData:
    REDIRECT_HOST: "http://127.0.0.1"
    REDIRECT_PORT: "9527"
    LOG_LEVEL: "INFO"
    # DB
    URL: "jdbc:postgresql://bitnami-postgresql-postgresql-ha-pgpool.postgresql.svc.cluster.local:5432/pulsar_manager"
    DRIVER_CLASS_NAME: "org.postgresql.Driver"
    # enables the "message peeking" feature
    PULSAR_PEEK_MESSAGE: "false"
  admin:
    ## Setting a value at existingSecret disables automatic creation of the secret for pulsar_manager admin credentials and instead uses an existing secret to initialize pulsar-manager
    ## The existing secret should have the following keys:
    ## DB_PASSWORD: <database password>
    ## DB_USERNAME: <database username>
    ## UI_PASSWORD: <UI password>
    ## UI_USERNAME: <UI username>
    #existingSecret: ""
    ui_username: "pulsar"
    ui_password: "pulsar"  # leave empty for random password
    db_username: "postgres"
    db_password: "123456"  # leave empty for random password
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
