### ISSUE TITLE
[Enchancement] Improve Pulsar Broker cache defaults to get better out-of-the-box performance

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar#23466]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Pulsar's defaults for broker cache aren't good for performance. This leads to wasted CPU and unnecessary network transfer costs in cloud environments.

### Solution

Here are some settings which would be better defaults.

- `maxMessagePublishBufferSizeInMB` - not broker cache related, but it's necessary to set it to an explicit value when fine-tuning broker cache settings so that direct memory OOM can be avoided. Default is 50% of direct memory. Set to `500`
- `managedLedgerCacheSizeMB` - the default is 20% of direct memory. It's better to set it to an explicit value to avoid direct memory OOM. Set to `512`
- `managedLedgerMaxReadsInFlightSizeInMB` - this feature is disabled by default. It's useful for avoiding direct memory OOM. Set to `100`
- `managedLedgerCacheEvictionTimeThresholdMillis` - the default `1000` is too low. Set to `10000`
- `managedLedgerCacheEvictionIntervalMs` - the default `10` is too low. Set to `5000` to avoid spending a lot of CPU with cache eviction.
- `managedLedgerMinimumBacklogCursorsForCaching` - the default `0` disables backlog cursors (catch-up read) caching. Set to `3`
- `managedLedgerMinimumBacklogEntriesForCaching` - the default `1000` is way too high. Set to `1`
- `managedLedgerMaxBacklogBetweenCursorsForCaching` - the default `10000` is way too low. Set to `2147483647` to disable the limit completely.

Sample settings for broker cache tuning:

yaml format:
```yaml
  maxMessagePublishBufferSizeInMB: 500
  managedLedgerCacheSizeMB: 512
  managedLedgerMaxReadsInFlightSizeInMB: 100
  managedLedgerCacheEvictionTimeThresholdMillis: 10000
  managedLedgerCacheEvictionIntervalMs: 5000
  managedLedgerMinimumBacklogCursorsForCaching: 3
  managedLedgerMinimumBacklogEntriesForCaching: 1
  managedLedgerMaxBacklogBetweenCursorsForCaching: 2147483647
```

`broker.conf` format:
```properties
maxMessagePublishBufferSizeInMB=500
managedLedgerCacheSizeMB=512
managedLedgerMaxReadsInFlightSizeInMB=100
managedLedgerCacheEvictionTimeThresholdMillis=10000
managedLedgerCacheEvictionIntervalMs=5000
managedLedgerMinimumBacklogCursorsForCaching=3
managedLedgerMinimumBacklogEntriesForCaching=1
managedLedgerMaxBacklogBetweenCursorsForCaching=2147483647
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
