### ISSUE TITLE
Fix pulsar-dashboard and docker-compose.yml,Port 8080 is valuable. We should release it.

### ISSUE THREAD

**Issue by leenux** [apache/pulsar#3051]
# Port 8080 is valuable. We should release it.
#### Expected behavior

Browser at pulsar-dashboard, should be have Tenants   |   Brokers   |   Topics   |   Clusters data.

#### Actual behavior

Browser at pulsar-dashboard, Non data:No tenants,,,etc.

#### Steps to reproduce

How can we reproduce the issue

- Create file:docker-compose.yml

```
version: '3.5'

networks:
  cherry-network:
    name: cherry-network
    driver: bridge

services:
  pulsar-0:
    container_name: pulsar-0
    hostname: pulsar-0
    image: apachepulsar/pulsar
    networks:
    - cherry-network
    environment:
    - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
#    volumes:
#    - ~/volumes/cherry/data/pulsar:/pulsar/data
    ports:
    - "6650:6650"
    - "9393:8080"

  pulsar-dashboard:
    container_name: pulsar-dashboard
    hostname: pulsar-dashboard
    networks:
    - cherry-network
    image: apachepulsar/pulsar-dashboard
    depends_on:
    - pulsar-0
    ports:
    - "83:80"
    environment:
    - SERVICE_URL=http://pulsar-0:9393
```
- docker-compose up
- browser at http://127.0.0.1:9393/admin/v2/persistent/public/functions/coordinate/stats it is ok
- browser at http://127.0.0.1:83 All data is null.
#### System configuration
**Pulsar version**: 2.2.0
