### ISSUE TITLE
Pulsar Dashboard Displays Very Little Information

### ISSUE THREAD

**Issue by phreed** [apache/pulsar#4044]
**Describe the bug**

The pulsar-dashboard does not display the information published by the pulsar cluster.

**To Reproduce**
1. Install a [bare metal pulsar](https://pulsar.apache.org/docs/en/deploy-bare-metal/)
    1. on an openstack cloud
    2. rather than a DNS server distribute identical /etc/hosts files to each of the vm's and the development machine
    2. 3 zookeeper each on their own vm
    3. 3 bookie/broker each pair on their own vm
2. On the development machine: Git [clone the pulsar](https://github.com/apache/pulsar/tree/v2.3.0)
    1. build the docker image : docker build -t apachepulsar/pulsar-dashboard dashboard
    2: export SERVICE_URL=http://ledge2:8080/
    3: docker run -p 80:80   -e SERVICE_URL=$SERVICE_URL   apachepulsar/pulsar-dashboard
3. Construct a 
    1. single tenant 
    2. several namespaces
    3. several topics

**Expected behavior**
The pulsar-dashboard should show clusters, tenants, namespaces, etc.

**Screenshots**
The pulsar  http server shows the presence of the cluster ...
![image(2)](https://user-images.githubusercontent.com/211644/56085932-cb504080-5e11-11e9-9937-6d0021605128.png)

The pulsar-dashboard apparently does not know about the cluster...
![image(1)](https://user-images.githubusercontent.com/211644/56085934-d014f480-5e11-11e9-95eb-7405442c48f9.png)

But no if you bring up one of the tabs having a CLUSTERS menu on the right there is the missing cluster...
![image](https://user-images.githubusercontent.com/211644/56085937-d5723f00-5e11-11e9-89ca-56dacef064ae.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 for the development machine and vm's

**Additional context**
Because /etc/hosts is used instead of DNS it is necessary to use the ledger2 ipaddr.
```
 export SERVICE_URL=http://128.60.107.171:8080/ 
```

**Comment by phreed** [comment]
The problem is with the name lookup. The messages returned by pulsar contain the urls for other objects. Those url contain host names and the docker image has no way of looking them up. This is easily remedied by changing the way the docker image is run.
```bash
docker run --network=host -p 80:80 -e SERVICE_URL=http://ledger2:8080 apachepulsar/pulsar-dashboard
```
Note the --network=host parameter.
In my case this amounts to granting access to the /etc/hosts files.
I would think that this would be the recommended way to run pulsar-dashboard in the "getting started" section of the documentation.

**Comment by ruudk** [comment]
I cannot get it to work either:
```
docker run -it \
                                  -p 6650:6650 \
                                  -p 8080:8080 \
                                  -v $PWD/pulsar-data:/pulsar/data \
                                  apachepulsar/pulsar:latest bin/pulsar standalone

docker run --network=host -p 80:80 -e SERVICE_URL=http://localhost:8080 apachepulsar/pulsar-dashboard
```

Dashboard doesn't show any tenants and clusters.

**Comment by phreed** [comment]
@ruudk Does the pulsar server respond to requests generally?
That is, if you point your browser to the $SERVICE_URL/admin/v2/clusters what do you get?
The pulsar-dashboad does is wrap the https://pulsar.apache.org/docs/latest/reference/RestApi/ .
If the pulsar server does not respond the dashboard will show nothing.

**Comment by phreed** [comment]
@ruudk Another issue may be a docker interaction.
How does a docker process with --network=host look up 'localhost'?
You might want to try providing either the hostname or ipaddr for the machine hosting your pulsar service.

**Comment by ruudk** [comment]
```json
// http://localhost:8080/admin/v2/clusters
[
  "standalone"
]
```

So that works. 

I think it would help a lot of the dashboard would just show errors when it cannot connect to the pulsar API. Right it just acts as if everything is empty and nothing is wrong.

When I run the dashboard with `--network=host` it says:
```
WARNING: Published ports are discarded when using host network mode
```

and it doesn't even come up.

Is there a way to somehow enable/view a debug log? To know what the error is?

**Comment by ruudk** [comment]
FYI: I run this all on my local machine with Docker.

**Comment by ruudk** [comment]
Even when I use `docker-compose` with this configuration it doesn't work:
```yaml
version: '3.3'

services:
    pulsar:
        image: apachepulsar/pulsar:latest
        hostname: pulsar
        command: bin/pulsar standalone --advertised-address 127.0.0.1
        ports:
            - 6650:6650
            - 8080:8080
        volumes:
            - ./pulsar-data:/pulsar/data
    dashboard:
        image: apachepulsar/pulsar-dashboard
        environment:
            SERVICE_URL: "http://pulsar:8080"
        ports:
            - 8081:80
```

**Comment by phreed** [comment]
Did you try...
docker run -p 80:80 -e SERVICE_URL=http://localhost:8080 apachepulsar/pulsar-dashboard

**Comment by ruudk** [comment]
I tried out this and it worked:
```
docker run -it \
                                                 -p 6650:6650 \
                                               -p 80:80  -p 8080:8080 \
                                                 -v $PWD/pulsar-data:/pulsar/data \
                                                 apachepulsar/pulsar-standalone:latest
```

Weird thing is that I have to wait a couple of minutes before data becomes visible. The UI is there, but it shows "No tenants" etc... but after a couple of minutes of starts to appear.

**Comment by sijie** [comment]
@ruudk in your docker compose case, you shouldn't use `--advertised-address 127.0.0.1`, you should either remove `--advertised-address`, or advertise an address that your dashboard docker can connect.

**Comment by ruudk** [comment]
@sijie Thanks. Solved it with this config:
```yaml
version: '3.3'

services:
    pulsar:
        image: apachepulsar/pulsar:latest
        command: bin/pulsar standalone
        ports:
            - 6650:6650
            - 8080:8080
        volumes:
            - ./pulsar-data:/pulsar/data
    dashboard:
        image: apachepulsar/pulsar-dashboard
        environment:
            SERVICE_URL: "http://pulsar:8080"
        ports:
            - 8081:80
```
