### ISSUE TITLE
[Kafka connect] Transformations are not working

### ISSUE THREAD

**Issue by willome** [apache/pulsar#4672]
**Describe the bug**
We can not use the Kafka Connect Transformations (https://docs.confluent.io/current/connect/transforms/index.html). This was tested with Debezium.

**To Reproduce**
From this : https://debezium.io/blog/2019/05/23/tutorial-using-debezium-connectors-with-apache-pulsar/

1. Start Database
```
docker run --rm --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=debezium -e MYSQL_USER=mysqluser -e MYSQL_PASSWORD=mysqlpw debezium/example-mysql:0.9
```
2. Start Pulsar 
```bin/pulsar standalone```

3. Start The debezium Mysql connector
```
bin/pulsar-admin source localrun  --sourceConfigFile debezium-mysql-source-config.yaml
```
with yaml 
```
tenant: "test"
namespace: "test-namespace"
name: "debezium-kafka-source"
topicName: "kafka-connect-topic"
archive: "connectors/pulsar-io-kafka-connect-adaptor-2.3.0.nar"

parallelism: 1

configs:
  ## sourceTask
  task.class: "io.debezium.connector.mysql.MySqlConnectorTask"
  database.hostname: "localhost"
  database.port: "3306"
  database.user: "debezium"
  database.password: "dbz"
  database.server.id: "184054"
  database.server.name: "dbserver1"
  database.whitelist: "inventory"
  database.history: "org.apache.pulsar.io.debezium.PulsarDatabaseHistory"
  database.history.pulsar.topic: "history-topic"
  database.history.pulsar.service.url: "pulsar://127.0.0.1:6650"
  key.converter: "org.apache.kafka.connect.json.JsonConverter"
  value.converter: "org.apache.kafka.connect.json.JsonConverter"
  pulsar.service.url: "pulsar://127.0.0.1:6650"
  offset.storage.topic: "offset-topic"
  transforms: "unwrap"
  transforms.unwrap.type: "io.debezium.transforms.UnwrapFromEnvelope"
```
4. Subscribe to topic
``` 
bin/pulsar-client consume -s "sub-products" public/default/dbserver1.inventory.products -n 0
```

**Expected behavior**
messages from topic modified by the transformation (without the Enveloppe)

**Comment by tuteng** [comment]
Sorry, I forgot to update the content here. This issue has only been discussed in slack before. 
This feature is deeply fused with kafka.  ExtractNewRecordState is used to replace the UnwrapFromEnvelope in the new version. https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java.

The class ExtractNewRecordState mainly processes two things, tombstones and addOperationHeader, which are related to the compaction of kafka, http://cloudurable.com/blog/kafka-architecture-log-compaction/index.html, Therefore, if this class ExtractNewRecordState is to be processed in Pulsar, the correct method is to trigger Pulsar's compaction after receiving this parameter. Of course, this is for the conversion of ExtractNewRecordState, and others transforms may have different processing logic.

I'm not sure if this transformations has a more suitable implementation in pulsar.
I'd like to hear your suggestions. @sijie @jiazhai @willome

**Comment by raghavi92** [comment]
Coming from Slack here. Would like to know if there's any scope and when we can expect custom kafka-like transforms in pulsar? For transforming messages before being published to a topic

**Comment by stevenodb** [comment]
👍

**Comment by fransguelinckx** [comment]
👍

**Comment by mingfang** [comment]
It appears that transforms are not working in general.
This is my config and I'm not seeing transforms working.
I'm also not seeing errors.  It is as if transforms are ignored completely.

```
tenant: "public"
namespace: "default"
name: "debezium-postgres-source"
topicName: "debezium-postgres-topic"
archive: "connectors/pulsar-io-debezium-postgres-2.6.1.nar"
parallelism: 1

configs:

    database.hostname: "worker-0.worker.citus-example"
    database.port: "5432"
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: "postgres"
    database.server.name: "dbserver1"
    schema.whitelist: "public"
    plugin.name: "pgoutput"

    pulsar.service.url: "pulsar://localhost:6650"

    transforms: "reroute"
    transforms.reroute.type: "io.debezium.transforms.ByLogicalTableRouter"
    transforms.reroute.topic.regex: ".*"
    transforms.reroute.topic.replacement: "foo"
    transforms.reroute.key.enforce.uniqueness: "false"
```
