### ISSUE TITLE
CDC Debezium Connector is generating unwanted topics

### ISSUE THREAD

**Issue by limadelrey** [apache/pulsar#5480]
When using CDC Debezium Connector with PostgreSQL we need to specify which tenant, namespace and topic we're using to persist change logs. However, Debezium is generating unwanted topics on both specified and "public" tenants. 

I'm using the following configurations in order to create a CDC Source Connector:

```
tenant: "limadelrey"
namespace: "first"
name: "first-limadelrey-source-connector"
topicName: "first-outbox-topic"
archive: "connectors/pulsar-io-debezium-postgres-2.4.1.nar"

parallelism: 1

configs:
  database.hostname: "first-service-db"
  database.port: "5432"
  database.user: "postgres"
  database.password: "postgres"
  database.dbname: "first"
  database.server.name: "first"
  table.whitelist: "limadelrey.outbox"
  pulsar.service.url: "pulsar://127.0.0.1:6650"
```

What I would expect to see the generation of two topics on the tenant/namespace combination that I specified before:

**Tenant/Namespace/Topic**
limadelrey/first/first-limadelrey-source-connector-debezium-offset-topic
limadelrey/first/first-outbox-topic

However, Debezium is generating the following topics (one seems to be the output of database.server.name + table.whitelist properties):

**Tenant/Namespace/Topic**
limadelrey/first/first-limadelrey-source-connector-debezium-offset-topic
limadelrey/first/first-outbox-topic
limadelrey/first/first.limadelrey.outbox
public/default/first-outbox-topic
