### ISSUE TITLE
Ability to specify an existing storage class instead of creating one when using Helm deployment

### ISSUE THREAD

**Issue by SakaSun** [apache/pulsar#5857]
**Is your feature request related to a problem? Please describe.**
Yes. With current aproach for specifying storage class in persistent volume claim it's not possible to customize the provisioner parameters. If the property 'storageClass' is declared the chart always create a new storage class with hardcoded parameters.

**Describe the solution you'd like**
It would be helpful if the chart template had an attribute 'storageClassName' to specify an existing storage class instead of creating one.
Example (values.yaml): 
```
  bookkeeper:
    volumes:
      ledgers:
        storageClassName: existent-storage-class
```

**Describe alternatives you've considered**
Delete and recreate the PVC with wanted storage class or manually create the PV.
