### ISSUE TITLE
Pulsar dashboard support getting authorization token from a file

### ISSUE THREAD

**Issue by dockerzhang** [apache/pulsar#5961]
**Describe the solution you'd like**
According to [administration-dashboard.md](https://github.com/apache/pulsar/blob/d20ce8851f375611c10aba0cdd32a345df7f2c48/site2/website/versioned_docs/version-2.4.2/administration-dashboard.md), dashboard container get authorization token from **JWT_TOKEN** environment. 
If the token was generated by Public/Private keys, it will be too long for **JWT_TOKEN**, It could be better to  support getting authorization token from a file for dashboard.

**Comment by dockerzhang** [comment]
I found **JWT_TOKEN** is good enough, this issue will be closed.

For docker run command:
```
export JWT_TOKEN=`cat token-value.txt`
```

For kubernetes cluster:
```
name: JWT_TOKEN
valueFrom:
  secretKeyRef:
    name: token-name
    key: token-value.txt
```
