### ISSUE TITLE
Unable to deploy on GKE, blocked at bookie.yaml step

### ISSUE THREAD

**Issue by pixime** [apache/pulsar#6135]
I'm trying to deploy pulsar on gke according to the Deploy pulsar components chapter in the documentation (https://pulsar.apache.org/docs/en/deploy-kubernetes/#deploy-pulsar-components). I use the apache-pulsar-2.5.0/deployment/kubernetes/google-kubernetes-engine yaml source directory. 

Steps :
- kubectl create -f zookeeper.yaml : OK, ok 3 replicated pods are running
- kubectl create -f cluster-matadata.yaml : OK, completed
- Kubectl create -f bookie.yaml failed.

I got the following error many times in the bookie-autorecovery logs: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error). 

As the zookeeper client StatefulSetport  is set to 2181, I suppose that the bookie-autorecovery is unable to connect to zookeeper. Naturally it ends by a CrashLoopBackOff.

Notice also that the bookie pods seem to be stuck, no logs.

My gke configuration is:
- 3 nodes
- n1-standard-4
- no autoscaling at the moment
- europe-west1

Any idea ?

**Comment by gaborho** [comment]
Hello, I have the same issue, but on AWS EKS. In case you remove PULSAR_PREFIX_ from all the keys defined in the ConfigMap of resource of bookie.yaml (in case of GKE) or in bookkeeper.yaml (in case of AWS) then it works.

**Comment by pixime** [comment]
What do you mean exactly ?

This is what I did:

**1. fist attempt:**
I commented only the PULSAR_PREFIX_zkServers variable
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookie-config
data:
  PULSAR_MEM: "\" -Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g\""
  PULSAR_GC: "\" -XX:+UseG1GC \""
  PULSAR_PREFIX_dbStorage_writeCacheMaxSizeMb: "1024"
  PULSAR_PREFIX_dbStorage_readAheadCacheMaxSizeMb: "1024"
  #PULSAR_PREFIX_zkServers: zk-0.zookeeper,zk-1.zookeeper,zk-2.zookeeper
  PULSAR_PREFIX_statsProviderClass: org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
  PULSAR_PREFIX_useHostNameAsBookieID: "true"
```
**But it failed**.

**2° attempt:**
With all PULSAR_PREFIX variables commented
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookie-config
data:
  PULSAR_MEM: "\" -Xms4g -Xmx4g -XX:MaxDirectMemorySize=4g\""
  PULSAR_GC: "\" -XX:+UseG1GC \""
  #PULSAR_PREFIX_dbStorage_writeCacheMaxSizeMb: "1024"
  #PULSAR_PREFIX_dbStorage_readAheadCacheMaxSizeMb: "1024"
  #PULSAR_PREFIX_zkServers: zk-0.zookeeper,zk-1.zookeeper,zk-2.zookeeper
  #PULSAR_PREFIX_statsProviderClass: org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
  #PULSAR_PREFIX_useHostNameAsBookieID: "true"
```
**And it failed as well**.
