### ISSUE TITLE
Strange CPU usage in standalone using Docker

### ISSUE THREAD

**Issue by nicolo-paganin** [apache/pulsar#6175]
**Describe the bug**
I am testing Pulsar 2.5.0 in the standalone mode using Docker 2.2.0.0. 
The container is created using docker-compose, this is the configuration:

```
pulsar:
    image: apachepulsar/pulsar:2.5.0
    ports:
      - "8080:8080"
      - "6650:6650"
    expose:
      - 8080
      - 6650
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
```

I noted a strange cpu usage, always ~40% cpu usage without doing any operation after the `docker-compose up`, look at this log

```top - 10:57:17 up 14:11,  0 users,  load average: 0.20, 0.37, 0.93
Tasks:   3 total,   1 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.6 us,  7.4 sy,  0.0 ni, 87.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7964.3 total,   4760.5 free,   1862.6 used,   1341.2 buff/cache
MiB Swap:   1024.0 total,    947.5 free,     76.5 used.   5851.5 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0 5324348 637228  30316 S  33.3   7.8   7:00.23 /usr/local/openjdk-8/bin/java -cp /pulsar/conf:::/pulsar/lib/*: -Dlog4j.configurationFile=log4j2.yaml -Djute.maxbuffer=10485760 -Djava.net.preferIPv4Stack=true -Dpulsar.allocator.exit_on_oom=true -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024 -Xms512m -Xm+
  610 root      20   0    5752   3652   3128 S   0.0   0.0   0:00.11 bash
  692 root      20   0    9616   3328   2968 R   0.0   0.0   0:00.00 top

top - 10:57:20 up 14:11,  0 users,  load average: 0.35, 0.40, 0.94
Tasks:   3 total,   1 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.7 us,  2.6 sy,  0.0 ni, 96.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7964.3 total,   4758.7 free,   1864.3 used,   1341.2 buff/cache
MiB Swap:   1024.0 total,    947.5 free,     76.5 used.   5849.8 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0 5324348 637228  30316 S  31.7   7.8   7:01.18 /usr/local/openjdk-8/bin/java -cp /pulsar/conf:::/pulsar/lib/*: -Dlog4j.configurationFile=log4j2.yaml -Djute.maxbuffer=10485760 -Djava.net.preferIPv4Stack=true -Dpulsar.allocator.exit_on_oom=true -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024 -Xms512m -Xm+
  610 root      20   0    5752   3652   3128 S   0.0   0.0   0:00.11 bash
  692 root      20   0    9616   3328   2968 R   0.0   0.0   0:00.00 top```

is this normal?
